#!/bin/sh

# If `make` on this system isn't GNU make, then use `gmake` instead.
if make --version 2>/dev/null | grep -q GNU; then
  MAKE=make
else
  MAKE=gmake
fi

# Rebuild if necessary, but stop if there's a problem building.
$MAKE || exit 1


# These are the arguments that will be passed `clang -cc1` which is invoked
# by the `clang` driver.
CC1_OPTS=`./invocation_builder.py ./FindDependencies.so find-deps`

# Run the plugin!
clang++ $CC1_OPTS -fsyntax-only `llvm-config --cxxflags` FindDependencies.cpp
